[workspace]
members = [
	"contract-address",
	"fixed-hash",
	"keccak-hash",
	"kvdb",
	"kvdb-memorydb",
	"kvdb-rocksdb",
	"kvdb-web",
	"parity-bytes",
	"parity-crypto",
	"parity-path",
	"plain_hasher",
	"rlp",
	"transaction-pool",
	"trace-time",
	"triehash",
	"uint",
	"tetsy-util-mem",
	"primitive-types",
	"ethereum-types",
	"ethbloom",
	"tetsy-util-mem/derive"
]
