[package]
description = "Large fixed-size integer arithmetic"
homepage = "http://tetcoin.org"
repository = "https://github.com/tetcoin/tetsy-common"
license = "MIT/Apache-2.0"
name = "uint-crate"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>"]
documentation = "https://docs.rs/uint-crate/"
readme = "README.md"
edition = "2018"

[dependencies]
byteorder = { version = "1", default-features = false }
rustc-hex = { version = "2.0", default-features = false }
quickcheck = { version = "0.6", optional = true }
crunchy = { version = "0.2", default-features = true }
static_assertions = "1.0.0"

[features]
default = ["std"]
std = ["byteorder/std", "rustc-hex/std", "crunchy/std"]

[[example]]
name = "modular"

[[test]]
name = "uint_tests"
required-features = ["std"]

[dev-dependencies]
criterion = "0.2.11"
num-bigint = "0.2"

[target.'cfg(unix)'.dev-dependencies]
rug = { version = "1.4", default-features = false, features = ["integer"] }

[[bench]]
name = "bigint"
harness = false
